name: CI
on: [push, pull_request]

jobs:
    tests:
        name: PHPUnit PHP ${{ matrix.php }} ${{ matrix.dependency }} (Symfony ${{ matrix.symfony }})
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                symfony:
                    - '5.4.*'
                    - '6.4.*'
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Configure Symfony
              run: composer config extra.symfony.require "${{ matrix.symfony }}"

            - name: Update project dependencies
              run: composer update --no-progress --ansi --prefer-stable

            - name: Validate composer
              run: composer validate --strict --no-check-lock

            - name: PHP-CS-Fixer
              run: vendor/bin/php-cs-fixer check -vv

            - name: PHPStan
              run: vendor/bin/phpstan analyse
